version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    image: dkoriaki/mariadb
    container_name: mariadb
    restart: always
    env_file :
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception-network

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/dkoriaki/data/mariadb_data

networks:
  inception-network:
