version: "3"

services:

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    image: dkoriaki/nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    networks:
      - inception-network

  wordpress:
    depends_on:
     - mariadb
    build: ./requirements/wordpress/
    image: dkoriaki/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    networks:
      - inception-network

  mariadb:
    build: ./requirements/mariadb/
    image: dkoriaki/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception-network

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /Users/dkoriaki/data/mariadb_data

  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /Users/dkoriaki/data/wordpress_data


networks:
  inception-network:
